#------------------------------#
#           TgSignal           #
#------------------------------#

#Включен ли плагин
enable: false
#Токен бота телеграм
bot_token: "сюда ваш токен"
#Кому будет отправляться уведолмение.
#Чтобы получить свой ID зайдите в бота в тг @getidsbot и вам покажет ваш ID его вставляем сюда
ChatIds:
- 12121231
#ну тут думаю всё понятно
messages:
  no-permission: "&cУ вас нету прав для выполнения этой команды!"
  reload: "&cКонфиг перезагружен"
  no-reload: "&cНе получилось перезапустить конфиг"
  #Пишет в тг когда наступаете на нить. Используйте %player% для отображения ника
  signal: "%player% был замечен"






